name: Deploy to GitHub Pages

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  deploy:
    uses: valiantlynx/valiantlynx-turborepo/.github/workflows/yarn-gh-pages.yml@main
    permissions:
      contents: write
    with:
      publish_dir: build
